versions:
  "13.0.2.14":
    folder: all
  "12.9.1.4":
    folder: all
  "12.8.4.1":
    folder: all
  "12.6.4.1":
    folder: all
  "12.5.3.2":
    folder: all
  "12.4.5.8":
    folder: all
  "12.3.4.1":
    folder: all
  "12.2.5.6":
    folder: all
  "12.1.3.1":
    folder: all
  "12.0.2.224":
    folder: all
  "11.11.3.6":
    folder: all
  "11.10.3.66":
    folder: all
  "11.9.2.110":
    folder: all
  "11.8.1.74":
    folder: all
  "11.7.4.6":
    folder: all
  "11.6.5.2":
    folder: all
