versions:
  "1.15.0.42":
    folder: all
  "1.14.1.1":
    folder: all
  "1.13.1.3":
    folder: all
  "1.11.1.6":
    folder: all
  "1.10.1.7":
    folder: all
  "1.9.1.3":
    folder: all
  "1.8.1.2":
    folder: all
  "1.7.2.10":
    folder: all
  "1.6.1.9":
    folder: all
  "1.5.1.14":
    folder: all
  "1.4.0.31":
    folder: all
  "1.3.1.18":
    folder: all
