versions:
  "15.1.0":
    folder: all
  "14.3.0":
    folder: all
  "13.3.0":
    folder: all
  "12.4.0":
    folder: all
  "11.5.0":
    folder: all
  "10.5.0":
    folder: all
  "9.5.0":
    folder: all
  "8.5.0":
    folder: all
