versions:
  "12.6.2.49":
    folder: all
  "12.5.10.65":
    folder: all
  "12.4.1.24":
    folder: all
  "12.3.1.170":
    folder: all
  "12.2.0.103":
    folder: all
  "12.1.3.153":
    folder: all
  "12.0.2.55":
    folder: all
  "11.7.5.86":
    folder: all
  "11.6.0.120":
    folder: all
