find_package(CBC QUIET)
find_package(CUOPT QUIET)
find_package(GCG QUIET)
find_package(GUROBI QUIET)
find_package(HIGHS QUIET)
find_package(MOSEK QUIET)
find_package(SCIP QUIET)
find_package(XPRESS QUIET)
find_package(ortoolsmp QUIET)
set(CBC_LIBS coin-cbc::coin-cbc)
set(CUOPT_LIBS cuopt::cuopt)
set(GCG_LIBS scip::scip)
set(GUROBI_LIBS gurobi::gurobi)
set(HIGHS_LIBS highs::highs)
set(MOSEK_LIBS mosek64)
set(SCIP_LIBS scip::scip)
set(XPRESS_LIBS xpress::xpress)
set(ortoolsmp_LIBS or-tools::or-tools)

find_package(small_vector REQUIRED)
link_libraries(gch::small_vector)
