if(WITH_NLOHMANN_JSON)
    find_package(nlohmann_json REQUIRED)
    link_libraries(nlohmann_json::nlohmann_json)
endif()
if(WITH_RAPIDJSON)
    find_package(RapidJSON REQUIRED)
    link_libraries(rapidjson)
    add_compile_definitions(TINYGLTF_USE_RAPIDJSON)
endif()
if(WITH_DRACO)
    find_package(draco REQUIRED)
    link_libraries(draco::draco)
    add_compile_definitions(TINYGLTF_ENABLE_DRACO)
endif()
if(WITH_STB_IMAGE)
    find_package(stb REQUIRED)
    link_libraries(stb::stb)
    add_compile_definitions(STB_IMAGE_IMPLEMENTATION)
else()
    add_compile_definitions(TINYGLTF_NO_STB_IMAGE)
endif()
if(WITH_STB_IMAGE_WRITE)
    find_package(stb REQUIRED)
    link_libraries(stb::stb)
    add_compile_definitions(STB_IMAGE_WRITE_IMPLEMENTATION)
else()
    add_compile_definitions(TINYGLTF_NO_STB_IMAGE_WRITE)
endif()
