versions:
  "3.0.2":
    folder: all
  "2.8.5":
    folder: all
  "2.7.0":
    folder: all
  "2.6.1":
    folder: all
  "2.5.0":
    folder: all
  "2.4.0":
    folder: all
  "2.3.2":
    folder: all
  "2.2.0":
    folder: all
  "2.1.0":
    folder: all
  "1.9.2":
    folder: all
  "1.8.1":
    folder: all
