versions:
  "13.0.88":
    folder: all
  "12.9.86":
    folder: all
  "12.8.93":
    folder: all
  "12.6.85":
    folder: all
  "12.5.82":
    folder: all
  "12.4.127":
    folder: all
  "12.3.101":
    folder: all
  "12.2.140":
    folder: all
  "12.1.105":
    folder: all
  "12.0.140":
    folder: all
