versions:
  "6.30.2":
    folder: all
  "5.29.4":
    folder: all
  "5.28.3":
    folder: all
  "5.27.0":
    folder: all
  "4.30.2":
    folder: all
  "4.25.3":
    folder: all
  "3.29.4":
    folder: all
  "3.21.12":
    folder: all
