versions:
  "6.32.0":
    folder: all
  "6.31.1":
    folder: all
  "5.29.5":
    folder: all
  "4.31.1":
    folder: all
  "4.25.8":
    folder: all
  "3.29.5":
    folder: all
  "3.21.12":
    folder: all
