versions:
  "11.4.1":
    folder: all
  "11.3.2":
    folder: all
  "11.2.1":
    folder: all
  "10.4.0":
    folder: all
  "9.0.0":
    folder: all
  "8.5.0":
    folder: all
  "7.3.0":
    folder: all
  "6.0.0":
    folder: all
