versions:
  "1.92.2b":
    folder: all
  "1.91.9b":
    folder: all
  "1.91.9":
    folder: all
  "1.90.9":
    folder: all
  "1.89.9":
    folder: all
  "1.88":
    folder: all
  "1.87":
    folder: all
  "1.86":
    folder: all
  "1.85":
    folder: all
