versions:
  "1.91.9b":
    folder: all
  "1.91.9":
    folder: all
  "1.91.8":
    folder: all
  "1.91.5":
    folder: all
  "1.90.9":
    folder: all
  "1.90.5":
    folder: all
  "1.89.9":
    folder: all
  "1.88":
    folder: all
  "1.87":
    folder: all
  "1.86":
    folder: all
  "1.85":
    folder: all
