versions:
  "13.0.48":
    folder: all
  "12.9.86":
    folder: all
  "12.8.93":
    folder: all
  "12.6.85":
    folder: all
  "12.5.82":
    folder: all
  "12.4.131":
    folder: all
  "12.3.107":
    folder: all
  "12.2.140":
    folder: all
  "12.1.105":
    folder: all
  "12.0.140":
    folder: all
  "11.8.89":
    folder: all
  "11.7.99":
    folder: all
  "11.6.124":
    folder: all
  "11.5.119":
    folder: all
  "11.4.152":
    folder: all
