versions:
  "4.1.1":
    folder: "binary"
  "4.0.3":
    folder: "binary"
  "3.31.8":
    folder: "binary"
  "3.30.5":
    folder: "binary"
  "3.29.7":
    folder: "binary"
  "3.28.6":
    folder: "binary"
  "3.27.9":
    folder: "binary"
  "3.26.6":
    folder: "binary"
  "3.25.3":
    folder: "binary"
  "3.24.4":
    folder: "binary"
  "3.23.5":
    folder: "binary"
  "3.22.6":
    folder: "binary"
  "3.21.7":
    folder: "binary"
  "3.20.6":
    folder: "binary"
  "3.19.8":
    folder: "binary"
