find_package(nlohmann_json REQUIRED)
find_package(minja REQUIRED)
link_libraries(nlohmann_json::nlohmann_json minja::minja)
if(LLAMA_BUILD_TOOLS)
    find_package(stb REQUIRED)
    find_package(miniaudio REQUIRED)
    link_libraries(stb::stb miniaudio::miniaudio)
endif()
if(LLAMA_BUILD_SERVER)
    find_package(httplib REQUIRED)
    link_libraries(httplib::httplib)
endif()
