versions:
  "13.0.0.50":
    folder: all
  "12.4.1.87":
    folder: all
  "12.3.3.100":
    folder: all
  "12.2.5.30":
    folder: all
  "12.1.1.14":
    folder: all
  "12.0.2.50":
    folder: all
  "11.8.0.86":
    folder: all
  "11.7.4.75":
    folder: all
  "11.6.3.124":
    folder: all
  "11.5.1.107":
    folder: all
  "11.4.0.110":
    folder: all
