versions:
  "r28b":
    folder: all
  "r27c":
    folder: all
  "r26d":
    folder: all
  "r25c":
    folder: all
  "r24":
    folder: all
  "r23c":
    folder: all
  "r22b":
    folder: all
  "r21e":
    folder: all
  "r20b":
    folder: all
  "r19c":
    folder: all
