versions:
  "2.3.0.6":
    folder: all
  "2.2.0.0":
    folder: all
  "2.1.0.9":
    folder: all
  "2.0.2.5":
    folder: all
  "1.7.0.1":
    folder: all
  "1.6.2.3":
    folder: all
  "1.5.0.3":
    folder: all
  "1.4.0.6":
    folder: all
  "1.3.3.2":
    folder: all
