versions:
  "1.6.47":
    folder: all
  "1.6.46":
    folder: all
  "1.6.45":
    folder: all
  "1.6.44":
    folder: all
  "1.6.43":
    folder: all
  "1.6.42":
    folder: all
  "1.6.41":
    folder: all
