find_package(dlpack REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(flann REQUIRED)
find_package(glew REQUIRED)
find_package(glfw3 REQUIRED)
find_package(imgui REQUIRED)
find_package(JPEG REQUIRED)
find_package(jsoncpp REQUIRED)
find_package(liblzf REQUIRED)
find_package(LibSGM REQUIRED)
find_package(OpenGL REQUIRED)
find_package(PNG REQUIRED)
find_package(rply REQUIRED)
find_package(spdlog REQUIRED)
find_package(stdgpu REQUIRED)
find_package(tinyobjloader REQUIRED)
find_package(urdfdom REQUIRED)

include_directories(third_party)  # for tomasakeninemoeller
include_directories(third_party/lbvh)
include_directories(third_party/lbvh_index)